language: ruby
cache: bundler
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
sudo: required
rvm:
- 2.3.1

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libgmp-dev
- sudo apt-get install -y build-essential
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- stack update
- stack setup

install:
- stack build
- bundle install
- bundle exec rake build
